In [30]:
import pandas as pd
import numpy as np

In [31]:
s1 = pd.Series(data=[10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [32]:
s2 = pd.Series(data=[100,200,300,400,500])
s2

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [33]:
s3 = pd.Series(data=[1000,2000,3000,4000,5000],index=list('vwxyz'))
s3

v    1000
w    2000
x    3000
y    4000
z    5000
dtype: int64

In [34]:
df = pd.DataFrame({'C1':s1, 'C2':s2})
df

   C1   C2
0  10  100
1  20  200
2  30  300
3  40  400
4  50  500

In [35]:
df = pd.DataFrame(data=np.random.randint(1,100,size=(1000,5)), columns=list('abcde'))
df

      a   b   c   d   e
0    34   9  86  25  10
1    62  95  38  20  49
2    28   3  86  37  85
3    12  62  78  90  79
4    61  11  23  36  43
..   ..  ..  ..  ..  ..
995  36  83  23   9  90
996  55  35  85  29  99
997  69  55  74  87  32
998  25  44  51  31  10
999  22  83  29  22  58

[1000 rows x 5 columns]

In [36]:
dataset = pd.read_csv('G:\\5Minutes python DSA\\Lecture10\\Session 10\\Car.csv')
dataset

    Age  Income  Car
0    28   37000    0
1    27   88000    0
2    28   59000    0
3    32   86000    0
4    33  149000    1
..  ...     ...  ...
95   28   89000    0
96   34   43000    0
97   30   79000    0
98   20   36000    0
99   26   80000    0

[100 rows x 3 columns]

In [37]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     100 non-null    int64
 1   Income  100 non-null    int64
 2   Car     100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB

In [38]:
dataset.head() # dataset ko samne se dekhna

   Age  Income  Car
0   28   37000    0
1   27   88000    0
2   28   59000    0
3   32   86000    0
4   33  149000    1

In [39]:
dataset.tail() # dataset ko back se dekhna

    Age  Income  Car
95   28   89000    0
96   34   43000    0
97   30   79000    0
98   20   36000    0
99   26   80000    0

In [40]:
dataset.Car.value_counts()

Car
0    93
1     7
Name: count, dtype: int64

In [41]:
dataset.rename(columns={'Car':'Target'})

    Age  Income  Target
0    28   37000       0
1    27   88000       0
2    28   59000       0
3    32   86000       0
4    33  149000       1
..  ...     ...     ...
95   28   89000       0
96   34   43000       0
97   30   79000       0
98   20   36000       0
99   26   80000       0

[100 rows x 3 columns]

In [42]:
dataset

    Age  Income  Car
0    28   37000    0
1    27   88000    0
2    28   59000    0
3    32   86000    0
4    33  149000    1
..  ...     ...  ...
95   28   89000    0
96   34   43000    0
97   30   79000    0
98   20   36000    0
99   26   80000    0

[100 rows x 3 columns]

In [43]:
dataset.rename(columns={'Car':'Target'},inplace=True)
dataset

    Age  Income  Target
0    28   37000       0
1    27   88000       0
2    28   59000       0
3    32   86000       0
4    33  149000       1
..  ...     ...     ...
95   28   89000       0
96   34   43000       0
97   30   79000       0
98   20   36000       0
99   26   80000       0

[100 rows x 3 columns]

In [44]:
dataset.shape[0]

100

In [45]:
dataset.head()   # first 5 rows
dataset.tail()   # last 5 rows

    Age  Income  Target
95   28   89000       0
96   34   43000       0
97   30   79000       0
98   20   36000       0
99   26   80000       0

In [46]:
dataset.iloc[2]   # 3rd row (index starts at 0)
dataset.loc[5]    # row with label/index = 5

Age          19
Income    21000
Target        0
Name: 5, dtype: int64

In [47]:
for index, row in dataset.iterrows():
    print(index, row["Income"])

0 37000
1 88000
2 59000
3 86000
4 149000
5 21000
6 72000
7 35000
8 89000
9 86000
10 80000
11 71000
12 71000
13 61000
14 55000
15 80000
16 57000
17 75000
18 52000
19 59000
20 59000
21 75000
22 72000
23 75000
24 53000
25 51000
26 61000
27 65000
28 32000
29 17000
30 84000
31 58000
32 31000
33 87000
34 68000
35 55000
36 63000
37 82000
38 107000
39 59000
40 25000
41 85000
42 68000
43 59000
44 89000
45 25000
46 89000
47 96000
48 30000
49 61000
50 74000
51 15000
52 45000
53 76000
54 50000
55 47000
56 15000
57 59000
58 75000
59 30000
60 135000
61 100000
62 90000
63 33000
64 38000
65 69000
66 86000
67 55000
68 71000
69 148000
70 47000
71 88000
72 115000
73 118000
74 43000
75 72000
76 28000
77 47000
78 22000
79 23000
80 34000
81 16000
82 71000
83 117000
84 43000
85 60000
86 66000
87 82000
88 41000
89 72000
90 32000
91 84000
92 26000
93 43000
94 70000
95 89000
96 43000
97 79000
98 36000
99 80000

In [48]:
import pandas as pd

data = {
    "Name": ["Aamir", "Ravi", "Neha"],
    "Age": [24, 30, 28]
}
datasets = pd.DataFrame(data)

In [49]:
datasets

    Name  Age
0  Aamir   24
1   Ravi   30
2   Neha   28

In [50]:
dataset.columns

Index(['Age', 'Income', 'Target'], dtype='object')

In [51]:
dataset[['Age','Target']]

    Age  Target
0    28       0
1    27       0
2    28       0
3    32       0
4    33       1
..  ...     ...
95   28       0
96   34       0
97   30       0
98   20       0
99   26       0

[100 rows x 2 columns]

In [52]:
dataset.loc[50]

Age          20
Income    74000
Target        0
Name: 50, dtype: int64

In [53]:
dataset.loc[50:60]

    Age  Income  Target
50   20   74000       0
51   26   15000       0
52   41   45000       0
53   31   76000       0
54   36   50000       0
55   40   47000       0
56   31   15000       0
57   46   59000       0
58   29   75000       0
59   26   30000       0
60   32  135000       1

In [54]:
dataset[(dataset['Income'] > 100000)]

    Age  Income  Target
4    33  149000       1
38   30  107000       1
60   32  135000       1
69   29  148000       1
72   34  115000       0
73   26  118000       0
83   32  117000       1

In [57]:
import pandas as pd
example = pd.read_csv('G:\\5Minutes python DSA\\Lecture10\\Session 10\\abc.csv')
example

  iteams  price
0      A   70.0
1      B    NaN
2      C   50.0
3      D    NaN
4      E   40.0
5      F   32.0
6      G   45.0
7      H   69.0
8      I    NaN
9      J    NaN

In [58]:
example['price'].notnull()

0     True
1    False
2     True
3    False
4     True
5     True
6     True
7     True
8    False
9    False
Name: price, dtype: bool

In [59]:
example[example['price'].isnull()]

  iteams  price
1      B    NaN
3      D    NaN
8      I    NaN
9      J    NaN

In [ ]:
example['price'].fillna(example['price'].max())

0    70.0
1    70.0
2    50.0
3    70.0
4    40.0
5    32.0
6    45.0
7    69.0
8    70.0
9    70.0
Name: price, dtype: float64

In [60]:
example['price'] = example['price'].fillna(example['price'].std())
example

  iteams      price
0      A  70.000000
1      B  15.517732
2      C  50.000000
3      D  15.517732
4      E  40.000000
5      F  32.000000
6      G  45.000000
7      H  69.000000
8      I  15.517732
9      J  15.517732

In [61]:
example['price'] = example['price'].fillna(example['price'].min())
example

  iteams      price
0      A  70.000000
1      B  15.517732
2      C  50.000000
3      D  15.517732
4      E  40.000000
5      F  32.000000
6      G  45.000000
7      H  69.000000
8      I  15.517732
9      J  15.517732

In [62]:
example['price'] = example['price'].fillna(example['price'].max())
example

  iteams      price
0      A  70.000000
1      B  15.517732
2      C  50.000000
3      D  15.517732
4      E  40.000000
5      F  32.000000
6      G  45.000000
7      H  69.000000
8      I  15.517732
9      J  15.517732

In [63]:
df.drop(['b'],axis='columns')

      a   c   d   e
0    34  86  25  10
1    62  38  20  49
2    28  86  37  85
3    12  78  90  79
4    61  23  36  43
..   ..  ..  ..  ..
995  36  23   9  90
996  55  85  29  99
997  69  74  87  32
998  25  51  31  10
999  22  29  22  58

[1000 rows x 4 columns]

In [64]:
df

      a   b   c   d   e
0    34   9  86  25  10
1    62  95  38  20  49
2    28   3  86  37  85
3    12  62  78  90  79
4    61  11  23  36  43
..   ..  ..  ..  ..  ..
995  36  83  23   9  90
996  55  35  85  29  99
997  69  55  74  87  32
998  25  44  51  31  10
999  22  83  29  22  58

[1000 rows x 5 columns]

In [65]:
df.drop(['b'],axis='columns',inplace=True)
df

      a   c   d   e
0    34  86  25  10
1    62  38  20  49
2    28  86  37  85
3    12  78  90  79
4    61  23  36  43
..   ..  ..  ..  ..
995  36  23   9  90
996  55  85  29  99
997  69  74  87  32
998  25  51  31  10
999  22  29  22  58

[1000 rows x 4 columns]

In [ ]:
# 🧩 isnull()
# Purpose: Checks for missing values (NaN) in your DataFrame.

# Returns: A DataFrame of True/False values.


import pandas as pd

data = {"Name": ["Aamir", "Ravi", None], "Age": [24, None, 28]}
df = pd.DataFrame(data)

print(df.isnull())

    Name    Age
0  False  False
1  False   True
2   True  False

In [67]:
# 🧩 fillna()
# Purpose: Fills missing values (NaN) with a specified value or method.

# Common uses:

# Replace with a fixed value:

df.fillna(0)

    Name   Age
0  Aamir  24.0
1   Ravi   0.0
2      0  28.0

In [72]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [73]:
df.fillna({"Age": df["Age"].mean()}, inplace=True)

In [74]:
import pandas as pd

data = {"Name": ["Aamir", "Ravi", None], "Age": [24, None, 28]}
df = pd.DataFrame(data)

# Safe way
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna("Unknown")

print(df)

      Name   Age
0    Aamir  24.0
1     Ravi  26.0
2  Unknown  28.0

In [ ]:
# df.fillna(method="ffill")
df.ffill()

      Name   Age
0    Aamir  24.0
1     Ravi  26.0
2  Unknown  28.0

In [84]:
df.bfill()

      Name   Age
0    Aamir  24.0
1     Ravi  26.0
2  Unknown  28.0

In [77]:
# Backward fill
df = df.bfill()

# Forward fill
df = df.ffill()

In [78]:
import pandas as pd

data = {"Name": ["Aamir", None, "Neha"], "Age": [24, None, 28]}
df = pd.DataFrame(data)

# Safe backward fill
df = df.bfill()

print(df)

    Name   Age
0  Aamir  24.0
1   Neha  28.0
2   Neha  28.0

In [79]:
df["Age"] = df["Age"].bfill()

In [80]:
df["Name"] = df["Name"].fillna("Unknown")
df["Age"]  = df["Age"].fillna(df["Age"].mean())

In [81]:
df.fillna({"Name": "Unknown", "Age": df["Age"].mean()}, inplace=True)

In [82]:
import pandas as pd

data = {"Name": ["Aamir", "Ravi", None], "Age": [24, None, 28]}
df = pd.DataFrame(data)

# Safe filling
df["Name"] = df["Name"].fillna("Unknown")
df["Age"]  = df["Age"].fillna(df["Age"].mean())

print(df)

      Name   Age
0    Aamir  24.0
1     Ravi  26.0
2  Unknown  28.0